/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.ChiTietHoaDon_DAO;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.KhachHang;
import entity.NhanVien;
import entity.SanPham;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.text.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class Panel_bill extends javax.swing.JPanel {
    private HoaDon_DAO hd_dao = new HoaDon_DAO();
    private CardLayout _this_card;
    private JPanel _this_pnl_card_parent;
    private NhanVien nv;
    private ChiTietHoaDon_DAO cthd_dao = new ChiTietHoaDon_DAO();
    private KhachHang_DAO kh_dao = new KhachHang_DAO();
    /**
     * Creates new form Panel_bill
     */
    public Panel_bill(NhanVien nv) {
        initComponents();

    	System.out.println("RUN");
        this.nv = nv;
        LoadDuLieuLenTable();
    }
    
    public void XoaHetDuLieu() {
        DefaultTableModel tmp = (DefaultTableModel) table_DSHD.getModel();
        tmp.getDataVector().removeAllElements();
    }
    
    public void LoadDuLieuLenTable() {
        ArrayList<HoaDon> dsHD = new ArrayList<HoaDon>();
        dsHD = hd_dao.getAllHD();
        
        DefaultTableModel model_dsHD = (DefaultTableModel) table_DSHD.getModel();
        
        for(HoaDon hd : dsHD) {
            Object[] obj = {hd.getMaHD(), hd.getNv().getFirst_name() + " " + hd.getNv().getLast_name(), 
                hd.getKh().getFirst_name() + " " + hd.getKh().getLast_name(), hd.getDate(), hd.getTong_tien()};
            
            model_dsHD.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_HoaDon = new javax.swing.JPanel();
        pnl_top = new javax.swing.JPanel();
        pnl_BoLoc = new javax.swing.JPanel();
        pnl_Date_LocTheoNgay = new javax.swing.JPanel();
        date_LocTheoNgay = new com.toedter.calendar.JDateChooser();
        btn_LocTheoNgay = new javax.swing.JButton();
        pnl_txt_LocTheoKH = new javax.swing.JPanel();
        txt_LocTheoKH = new javax.swing.JTextField();
        btn_LocTheoKH = new javax.swing.JButton();
        pn_LocTheoNV = new javax.swing.JPanel();
        txt_LocTheoKH1 = new javax.swing.JTextField();
        btn_LocTheoKH1 = new javax.swing.JButton();
        pnl_center = new javax.swing.JPanel();
        pnl_HD_TimKiem = new javax.swing.JPanel();
        txt_TimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnl_Tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DSHD = new javax.swing.JTable();
        pnl_XuatHoaDon = new javax.swing.JPanel();
        btn_XemChiTiet = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1280, 362));
        setPreferredSize(new java.awt.Dimension(476, 450));
        setLayout(new java.awt.BorderLayout());

        pnl_HoaDon.setLayout(new java.awt.BorderLayout());

        pnl_top.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_top.setPreferredSize(new java.awt.Dimension(10, 100));
        pnl_top.setLayout(new java.awt.BorderLayout());

        pnl_BoLoc.setPreferredSize(new java.awt.Dimension(10, 100));
        pnl_BoLoc.setLayout(new java.awt.GridLayout(1, 3));

        pnl_Date_LocTheoNgay.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc Theo Ngày"));
        pnl_Date_LocTheoNgay.setLayout(new java.awt.BorderLayout());

        date_LocTheoNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_LocTheoNgayPropertyChange(evt);
            }
        });
        pnl_Date_LocTheoNgay.add(date_LocTheoNgay, java.awt.BorderLayout.CENTER);

        btn_LocTheoNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_LocTheoNgay.setPreferredSize(new java.awt.Dimension(70, 43));
        btn_LocTheoNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LocTheoNgayMouseClicked(evt);
            }
        });
        pnl_Date_LocTheoNgay.add(btn_LocTheoNgay, java.awt.BorderLayout.LINE_END);

        pnl_BoLoc.add(pnl_Date_LocTheoNgay);

        pnl_txt_LocTheoKH.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc Theo Khách Hàng"));
        pnl_txt_LocTheoKH.setLayout(new java.awt.BorderLayout());

        txt_LocTheoKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_LocTheoKH.setText("0123456789");
        pnl_txt_LocTheoKH.add(txt_LocTheoKH, java.awt.BorderLayout.CENTER);

        btn_LocTheoKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_LocTheoKH.setPreferredSize(new java.awt.Dimension(70, 43));
        btn_LocTheoKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LocTheoKHMouseClicked(evt);
            }
        });
        pnl_txt_LocTheoKH.add(btn_LocTheoKH, java.awt.BorderLayout.LINE_END);

        pnl_BoLoc.add(pnl_txt_LocTheoKH);

        pn_LocTheoNV.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc Theo Nhân Viên"));
        pn_LocTheoNV.setLayout(new java.awt.BorderLayout());

        txt_LocTheoKH1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_LocTheoKH1.setText("0123456789");
        pn_LocTheoNV.add(txt_LocTheoKH1, java.awt.BorderLayout.CENTER);

        btn_LocTheoKH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_LocTheoKH1.setPreferredSize(new java.awt.Dimension(70, 43));
        btn_LocTheoKH1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LocTheoKH1MouseClicked(evt);
            }
        });
        pn_LocTheoNV.add(btn_LocTheoKH1, java.awt.BorderLayout.LINE_END);

        pnl_BoLoc.add(pn_LocTheoNV);

        pnl_top.add(pnl_BoLoc, java.awt.BorderLayout.CENTER);

        pnl_HoaDon.add(pnl_top, java.awt.BorderLayout.PAGE_START);

        pnl_center.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Hóa Đơn"));
        pnl_center.setPreferredSize(new java.awt.Dimension(468, 500));
        pnl_center.setLayout(new java.awt.BorderLayout());

        pnl_HD_TimKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
        pnl_HD_TimKiem.setPreferredSize(new java.awt.Dimension(10, 80));

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TimKiem.setPreferredSize(new java.awt.Dimension(700, 50));
        pnl_HD_TimKiem.add(txt_TimKiem);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        pnl_HD_TimKiem.add(jButton1);

        pnl_center.add(pnl_HD_TimKiem, java.awt.BorderLayout.PAGE_START);

        pnl_Tabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnl_Tabel.setPreferredSize(new java.awt.Dimension(458, 400));
        pnl_Tabel.setLayout(new java.awt.BorderLayout());

        table_DSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Nhân Viên", "Khách Hàng", "Ngày Tạo Hóa Đơn", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(table_DSHD);

        pnl_Tabel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnl_center.add(pnl_Tabel, java.awt.BorderLayout.CENTER);

        pnl_XuatHoaDon.setPreferredSize(new java.awt.Dimension(10, 60));

        btn_XemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XemChiTiet.setText("Xem chi tiết");
        btn_XemChiTiet.setPreferredSize(new java.awt.Dimension(200, 50));
        btn_XemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XemChiTietMouseClicked(evt);
            }
        });
        pnl_XuatHoaDon.add(btn_XemChiTiet);

        pnl_center.add(pnl_XuatHoaDon, java.awt.BorderLayout.SOUTH);

        pnl_HoaDon.add(pnl_center, java.awt.BorderLayout.CENTER);

        add(pnl_HoaDon, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XemChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XemChiTietMouseClicked
        // TODO add your handling code here:
        int r = table_DSHD.getSelectedRow();

        if(r >= 0) {
            ArrayList<Object[]> obj = cthd_dao.getDSSP_TheoMaHD(table_DSHD.getValueAt(r, 0).toString());
            HoaDon hd = hd_dao.getHD_TheoMa(table_DSHD.getValueAt(r, 0).toString());
            new DiaLog_DSSP_HD(hd, obj).setVisible(true);
        }

    }//GEN-LAST:event_btn_XemChiTietMouseClicked

    private void date_LocTheoNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_LocTheoNgayPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_date_LocTheoNgayPropertyChange

    private void btn_LocTheoNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LocTheoNgayMouseClicked
        // TODO add your handling code here:
         SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBatDau = df.format(date_LocTheoNgay.getDate());
         Date currentDate = date_LocTheoNgay.getDate();

        // Chuyển đổi ngày thành lớp Calendar
        Calendar calendarInstance = Calendar.getInstance();
        calendarInstance.setTime(currentDate);

        // Thêm một ngày để lấy ngày hôm sau
        calendarInstance.add(Calendar.DAY_OF_MONTH, 1);

        // Lấy ngày hôm sau
        Date nextDay = calendarInstance.getTime();
        String ngayKT = df.format(nextDay);
        
        XoaHetDuLieu();
        
        ArrayList<HoaDon> dsHD = hd_dao.TimHoaDonTheoThoiGian(ngayBatDau, ngayKT);
        
         DefaultTableModel model_dsHD = (DefaultTableModel) table_DSHD.getModel();
        
        for(HoaDon hd : dsHD) {
            Object[] obj = {hd.getMaHD(), hd.getNv().getLast_name(), hd.getKh().getLast_name(), hd.getDate(),hd.getTong_tien()};
            
            model_dsHD.addRow(obj);
        }
    }//GEN-LAST:event_btn_LocTheoNgayMouseClicked

    private void btn_LocTheoKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LocTheoKHMouseClicked
        // TODO add your handling code here:
        if(txt_LocTheoKH.getText().equals("")) {
            XoaHetDuLieu();
            LoadDuLieuLenTable();
        } else {
            ArrayList<HoaDon> dsHD = hd_dao.LocTheoKH(txt_LocTheoKH.getText());

            XoaHetDuLieu();
            DefaultTableModel model_dsHD = (DefaultTableModel) table_DSHD.getModel();
        
            for(HoaDon hd : dsHD) {
                Object[] obj = {hd.getMaHD(), hd.getNv().getLast_name(), hd.getKh().getLast_name(), hd.getDate(),hd.getTong_tien()};

                model_dsHD.addRow(obj);
            }
        }
    }//GEN-LAST:event_btn_LocTheoKHMouseClicked

    private void btn_LocTheoKH1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LocTheoKH1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LocTheoKH1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LocTheoKH;
    private javax.swing.JButton btn_LocTheoKH1;
    private javax.swing.JButton btn_LocTheoNgay;
    private javax.swing.JButton btn_XemChiTiet;
    private com.toedter.calendar.JDateChooser date_LocTheoNgay;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_LocTheoNV;
    private javax.swing.JPanel pnl_BoLoc;
    private javax.swing.JPanel pnl_Date_LocTheoNgay;
    private javax.swing.JPanel pnl_HD_TimKiem;
    private javax.swing.JPanel pnl_HoaDon;
    private javax.swing.JPanel pnl_Tabel;
    private javax.swing.JPanel pnl_XuatHoaDon;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JPanel pnl_txt_LocTheoKH;
    private javax.swing.JTable table_DSHD;
    private javax.swing.JTextField txt_LocTheoKH;
    private javax.swing.JTextField txt_LocTheoKH1;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
