/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.ChiTietHoaDon_DAO;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.SanPham_DAO;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.SanPham;
import entity.KhachHang;
import entity.NhanVien;
import java.awt.Component;
import java.awt.FlowLayout;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Asus
 */
public class Panel_cart extends javax.swing.JPanel {
    private JTextField txt_TimKiem;
    private JPanel pnl_TimKiem;
    private SanPham_DAO sp_dao;
    private KhachHang_DAO kh_dao = new KhachHang_DAO();
    private HoaDon_DAO hd_dao;
    private ChiTietHoaDon_DAO cthd_dao = new ChiTietHoaDon_DAO();
    private DefaultTableModel model_DSSP;
    private NhanVien nv;
    private ArrayList<ChiTietHoaDon> dsCTHD;
    private KhachHang kh = null;
    private double tongTienThanhToan = 0;
    private double tienVon = 0;
    private double tongThue = 0;
    private double tongKM = 0;
    private static ArrayList<SanPham> ds_sp_temp = new ArrayList<>();
    private static ArrayList<Object[]> obj_sp_temp = new ArrayList<>();
    /**
     * Creates new form Panel_product
     */
    public Panel_cart(NhanVien nv) {
        sp_dao = new SanPham_DAO();
        hd_dao = new HoaDon_DAO();
        this.dsCTHD = dsCTHD;
        this.nv = nv;
        initComponents();
        
        setTxt_MaHD_TuPhatSinh();
    }
    
    public void setTxt_MaHD_TuPhatSinh() {
        txt_MaHD.setText(hd_dao.phatSinhMaTuDong());
    }
    
    public void XoaTable_DSSP() {
        DefaultTableModel temp = (DefaultTableModel) table_DanhSachSP.getModel();
        temp.getDataVector().removeAllElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_thongTin = new javax.swing.JPanel();
        pnl_thongTin_KH = new javax.swing.JPanel();
        pnl_timKH = new javax.swing.JPanel();
        txt_TimKH = new javax.swing.JTextField();
        lb_TimKH = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JButton();
        pnl_TimKH_row1 = new javax.swing.JPanel();
        lb_DiemTichLuy = new javax.swing.JLabel();
        txt_DiemTichLuy = new javax.swing.JTextField();
        lb_TenKH = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        pnl_ThongTin_HD = new javax.swing.JPanel();
        lb_MaHD = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        pnl_center = new javax.swing.JPanel();
        pnl_TimSP = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        txt_TimSP = new javax.swing.JTextField();
        pnl_DanhSachSP = new javax.swing.JPanel();
        scroll_DanhSachSP = new javax.swing.JScrollPane();
        table_DanhSachSP = new javax.swing.JTable();
        pnl_thanhToan = new javax.swing.JPanel();
        lb_TongThuCa1 = new javax.swing.JLabel();
        lb_TongThuCa3 = new javax.swing.JLabel();
        txt_ThanhToan = new javax.swing.JTextField();
        txt_TongKM = new javax.swing.JTextField();
        btn_ThanhToan = new javax.swing.JButton();
        lbl_TongThue = new javax.swing.JLabel();
        txt_SudungTichDiem = new javax.swing.JTextField();
        txt_TongThue = new javax.swing.JTextField();
        lbl_TienNhan1 = new javax.swing.JLabel();
        txt_TienNhan = new javax.swing.JTextField();
        lb_TongThuCa4 = new javax.swing.JLabel();
        txt_TienThoi = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        pnl_thongTin.setPreferredSize(new java.awt.Dimension(10, 115));
        pnl_thongTin.setLayout(new java.awt.BorderLayout());

        pnl_thongTin_KH.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_thongTin_KH.setPreferredSize(new java.awt.Dimension(659, 100));
        pnl_thongTin_KH.setLayout(new java.awt.BorderLayout());

        pnl_timKH.setBackground(new java.awt.Color(255, 0, 0));
        pnl_timKH.setPreferredSize(new java.awt.Dimension(218, 50));
        pnl_timKH.setLayout(new java.awt.BorderLayout());

        txt_TimKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_timKH.add(txt_TimKH, java.awt.BorderLayout.CENTER);

        lb_TimKH.setBackground(new java.awt.Color(255, 0, 0));
        lb_TimKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TimKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TimKH.setText("Khách Hàng");
        lb_TimKH.setPreferredSize(new java.awt.Dimension(100, 16));
        pnl_timKH.add(lb_TimKH, java.awt.BorderLayout.WEST);

        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_TimKiem.setPreferredSize(new java.awt.Dimension(50, 27));
        btn_TimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimKiemMouseClicked(evt);
            }
        });
        pnl_timKH.add(btn_TimKiem, java.awt.BorderLayout.EAST);

        pnl_thongTin_KH.add(pnl_timKH, java.awt.BorderLayout.NORTH);

        pnl_TimKH_row1.setPreferredSize(new java.awt.Dimension(20, 30));
        pnl_TimKH_row1.setLayout(new java.awt.GridBagLayout());

        lb_DiemTichLuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_DiemTichLuy.setText("Điểm tích lũy:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 100, 13, 0);
        pnl_TimKH_row1.add(lb_DiemTichLuy, gridBagConstraints);

        txt_DiemTichLuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_DiemTichLuy.setEnabled(false);
        txt_DiemTichLuy.setPreferredSize(new java.awt.Dimension(70, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 162;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 34, 13, 7);
        pnl_TimKH_row1.add(txt_DiemTichLuy, gridBagConstraints);

        lb_TenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TenKH.setText("Tên: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 26, 13, 0);
        pnl_TimKH_row1.add(lb_TenKH, gridBagConstraints);

        txt_TenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TenKH.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 162;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 26, 13, 0);
        pnl_TimKH_row1.add(txt_TenKH, gridBagConstraints);

        pnl_thongTin_KH.add(pnl_TimKH_row1, java.awt.BorderLayout.CENTER);

        pnl_thongTin.add(pnl_thongTin_KH, java.awt.BorderLayout.CENTER);

        pnl_ThongTin_HD.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_ThongTin_HD.setPreferredSize(new java.awt.Dimension(500, 10));

        lb_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_MaHD.setText("Mã HD:");
        pnl_ThongTin_HD.add(lb_MaHD);

        txt_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaHD.setEnabled(false);
        txt_MaHD.setPreferredSize(new java.awt.Dimension(250, 50));
        pnl_ThongTin_HD.add(txt_MaHD);

        pnl_thongTin.add(pnl_ThongTin_HD, java.awt.BorderLayout.EAST);

        add(pnl_thongTin, java.awt.BorderLayout.NORTH);

        pnl_center.setPreferredSize(new java.awt.Dimension(456, 300));
        pnl_center.setLayout(new java.awt.BorderLayout());

        pnl_TimSP.setLayout(new java.awt.BorderLayout());

        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.setPreferredSize(new java.awt.Dimension(150, 43));
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMouseClicked(evt);
            }
        });
        pnl_TimSP.add(btn_Them, java.awt.BorderLayout.EAST);

        txt_TimSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TimSP.setPreferredSize(new java.awt.Dimension(80, 50));
        pnl_TimSP.add(txt_TimSP, java.awt.BorderLayout.CENTER);

        pnl_center.add(pnl_TimSP, java.awt.BorderLayout.NORTH);

        pnl_DanhSachSP.setPreferredSize(new java.awt.Dimension(456, 300));
        pnl_DanhSachSP.setLayout(new java.awt.BorderLayout());

        scroll_DanhSachSP.setPreferredSize(new java.awt.Dimension(456, 300));

        table_DanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên mặt hàng", "Loại", "Số lượng", "Thuế", "KM", "Đơn giá (có thuế)", "Thành tiền"
            }
        ));
        table_DanhSachSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DanhSachSPMouseClicked(evt);
            }
        });
        scroll_DanhSachSP.setViewportView(table_DanhSachSP);

        pnl_DanhSachSP.add(scroll_DanhSachSP, java.awt.BorderLayout.CENTER);

        pnl_thanhToan.setPreferredSize(new java.awt.Dimension(10, 150));
        pnl_thanhToan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_TongThuCa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TongThuCa1.setText("Tổng KM:");
        pnl_thanhToan.add(lb_TongThuCa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 70, 20));

        lb_TongThuCa3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TongThuCa3.setText("Sử dụng tích điểm:");
        pnl_thanhToan.add(lb_TongThuCa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txt_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_ThanhToan.setForeground(new java.awt.Color(255, 51, 51));
        txt_ThanhToan.setText("0");
        pnl_thanhToan.add(txt_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 390, 60));

        txt_TongKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TongKM.setText("0.00");
        pnl_thanhToan.add(txt_TongKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 230, 40));

        btn_ThanhToan.setBackground(new java.awt.Color(255, 51, 51));
        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThanhToanMouseClicked(evt);
            }
        });
        pnl_thanhToan.add(btn_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 60));

        lbl_TongThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_TongThue.setText("Tổng thuế:");
        pnl_thanhToan.add(lbl_TongThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 80, 20));

        txt_SudungTichDiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_SudungTichDiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SudungTichDiemKeyReleased(evt);
            }
        });
        pnl_thanhToan.add(txt_SudungTichDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 390, 40));

        txt_TongThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_thanhToan.add(txt_TongThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 230, 40));

        lbl_TienNhan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_TienNhan1.setText("Tiền nhận: ");
        pnl_thanhToan.add(lbl_TienNhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 80, 20));

        txt_TienNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TienNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TienNhanKeyReleased(evt);
            }
        });
        pnl_thanhToan.add(txt_TienNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 230, 40));

        lb_TongThuCa4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TongThuCa4.setText("Tiền thối:");
        pnl_thanhToan.add(lb_TongThuCa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 70, 20));

        txt_TienThoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TienThoi.setText("0.00");
        pnl_thanhToan.add(txt_TienThoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 230, 40));

        pnl_DanhSachSP.add(pnl_thanhToan, java.awt.BorderLayout.PAGE_END);

        pnl_center.add(pnl_DanhSachSP, java.awt.BorderLayout.CENTER);

        add(pnl_center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseClicked
        String maSP = txt_TimSP.getText();
        SanPham sp = sp_dao.getSP_TheoMa(maSP);
        
        if(sp != null) {
            ds_sp_temp.add(sp);
            
            // Nhập số lượng sản phẩm
            int soLuong = Integer.parseInt(JOptionPane.showInputDialog(null, "Nhập số lượng", 0));
            
            // set text tongthue tongKM tienVon
            tienVon += sp.getGiaNhapHang() * soLuong;
            tongKM += sp.getkM().getMuc_giam_gia() < 1 
                    ? sp.getkM().getMuc_giam_gia() * soLuong * sp.getGiaBan()
                    : sp.getkM().getMuc_giam_gia() * soLuong;
            tongThue += sp.getThue() * soLuong * sp.getGiaBan();
            
            txt_TongThue.setText(String.format("%.2f", tongThue));
            txt_TongKM.setText(String.format("%.2f", tongKM));
            
            int n = table_DanhSachSP.getModel().getRowCount();
            // Kiểm tra sản phẩm trùng lặp: cộng dồn số lượng và thành tiền
            for(int i = 0; i < n; ++i) {
                String maSP_Cheked = table_DanhSachSP.getModel().getValueAt(i, 0).toString();
                if(maSP_Cheked.compareTo(maSP) == 0) {
                    int soLuongHienTai = Integer.parseInt(table_DanhSachSP.getModel().getValueAt(i, 3).toString());
                    int soLuongMoi = soLuongHienTai + soLuong;
                    table_DanhSachSP.getModel().setValueAt(soLuongMoi, i, 3);
                    
                    table_DanhSachSP.getModel().setValueAt(
                            Double.parseDouble(table_DanhSachSP.getValueAt(i, 6).toString()) * soLuongMoi, i, 7);
                    return;
                }
            }
            
            // Them sp vao gio hang
            double muc_giam_gia = sp.getkM().getMuc_giam_gia();
            double donGia_coThue_coKM = muc_giam_gia < 1
                    ? (sp.getGiaBan() * (1 - muc_giam_gia + sp.getThue()))
                    : (sp.getGiaBan() * (1 + sp.getThue()) - muc_giam_gia) ;
            Object[] obj = {sp.getMaSP(), sp.getTenSP(), sp.getLoaiSP(), soLuong, sp.getThue() * 100 + "%", 
                                        sp.getkM().getMo_ta(), donGia_coThue_coKM ,donGia_coThue_coKM * soLuong};
            model_DSSP = (DefaultTableModel)table_DanhSachSP.getModel();
            model_DSSP.addRow(obj);
            
            obj_sp_temp.add(obj);
            
            // Lấy số lượng hàng đang có
            n = table_DanhSachSP.getModel().getRowCount();
            
            // Tính tổng tiền thanh toán
            for(int i = 0; i < n; ++i) {
                tongTienThanhToan += (Double) table_DanhSachSP.getValueAt(i, 7);
            }
            txt_ThanhToan.setText(tongTienThanhToan + "");
            tongTienThanhToan = 0;
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm");
        }
    }//GEN-LAST:event_btn_ThemMouseClicked

    // ========================== TIM KIEM KHACH HANG ===================
    // =========================
    // ========================
    private void btn_TimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimKiemMouseClicked
        // TODO add your handling code here:
        String maKH_searched = txt_TimKH.getText();
        
        kh = kh_dao.getKH_TheoMa(maKH_searched);
        if(kh != null) {
            txt_TenKH.setText(kh.getFirst_name()+ " " + kh.getLast_name());
            txt_DiemTichLuy.setText(kh.getTieuPhiTichLuy() + "");
            txt_TimKH.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Khách hàng chưa đăng ký thành viên!!!");
        }
    }//GEN-LAST:event_btn_TimKiemMouseClicked

    private void txt_SudungTichDiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SudungTichDiemKeyReleased
        double tienNhan = Double.parseDouble(txt_TienNhan.getText());
        double tienThanhToan = Double.parseDouble(txt_ThanhToan.getText());
        
        double suDungTichDiem = 0;
        if(txt_SudungTichDiem.getText().compareTo("") != 0)
        {
            suDungTichDiem = Double.parseDouble(txt_SudungTichDiem.getText());
        }
        
        double tienThoi = tienNhan + suDungTichDiem - tienThanhToan;
        txt_TienThoi.setText(tienThoi + "");
    }//GEN-LAST:event_txt_SudungTichDiemKeyReleased

    private void btn_ThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThanhToanMouseClicked
        // Kiểm tra thông số
        if(txt_TienNhan.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Chưa nhận tiền của khách!!!");
        } else if(Double.parseDouble(txt_TienNhan.getText()) < tongTienThanhToan) {
            JOptionPane.showMessageDialog(this, "Chưa đủ tiền thanh toán !!!");
        } else {
            String maKH = kh == null ? "" : kh.getMaKH();
            String tenKH = kh == null ? "" : kh.getFirst_name() + " " + kh.getLast_name();

            // Ngày tạo hóa đơn
            LocalDateTime ngayTao = LocalDateTime.now();

            double tienKhachDua = Double.parseDouble(txt_TienNhan.getText());

            double suDungTichDiem = !txt_SudungTichDiem.getText().equals("") 
                    ? Double.parseDouble(txt_SudungTichDiem.getText())
                    : 0;

            // Tao Hoa Don
            HoaDon hd = new HoaDon(hd_dao.phatSinhMaTuDong(), nv, kh, ngayTao, Double.parseDouble(txt_TienNhan.getText()), 
                    Double.parseDouble(txt_TienThoi.getText()), 
                    tienVon, tongKM, tongThue, tongTienThanhToan, suDungTichDiem);

            // Them hoa don thanh cong
            if(hd_dao.themHD(hd)) {
                // Luu chi tiet hoa don
                for(int i = 0; i < table_DanhSachSP.getRowCount(); ++i) {
                    String maSP_CTHD = table_DanhSachSP.getValueAt(i, 0).toString();
                    int soLuong = Integer.parseInt(table_DanhSachSP.getValueAt(i, 3).toString());
                    double thanhTien = Double.parseDouble(table_DanhSachSP.getValueAt(i, 7).toString());
                    
                    ChiTietHoaDon cthd = new ChiTietHoaDon(hd, ds_sp_temp.get(i), 
                            soLuong, tongKM, thanhTien);
                    cthd_dao.ThemCTHDVaoCSDL(cthd);
                }
                
                JOptionPane.showMessageDialog(this, "Lưu hóa đơn thành công!!!");
                
                XoaTable_DSSP();
                txt_TongThue.setText("");
                txt_TongKM.setText("");
                txt_ThanhToan.setText("");
                txt_SudungTichDiem.setText("");
                txt_TimSP.setText("");
                txt_TienNhan.setText("");
                txt_TienThoi.setText("");
                tongThue = 0;
                tongKM = 0;
                tongTienThanhToan = 0;
                
//                new DiaLog_DSSP_HD(hd, obj_sp_temp).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, vui lòng thử lại!!!");
            }
        }
    }//GEN-LAST:event_btn_ThanhToanMouseClicked

    private void table_DanhSachSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DanhSachSPMouseClicked
        int r = table_DanhSachSP.getSelectedRow();
        
        if(r >= 0) {
            txt_TimSP.setText(table_DanhSachSP.getValueAt(r, 0).toString());
        }
    }//GEN-LAST:event_table_DanhSachSPMouseClicked

    private void txt_TienNhanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TienNhanKeyReleased
        // TODO add your handling code here:
        double tienNhan = txt_TienNhan.getText().equals("") ? 0 : Double.parseDouble(txt_TienNhan.getText());
        double tienThanhToan = Double.parseDouble(txt_ThanhToan.getText());
        
        double suDungTichDiem = 0;
        if(txt_SudungTichDiem.getText().compareTo("") != 0)
        {
            suDungTichDiem = Double.parseDouble(txt_SudungTichDiem.getText());
        }
        
        double tienThoi = tienNhan + suDungTichDiem - tienThanhToan;
        
        txt_TienThoi.setText(tienThoi + "");
    }//GEN-LAST:event_txt_TienNhanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JLabel lb_DiemTichLuy;
    private javax.swing.JLabel lb_MaHD;
    private javax.swing.JLabel lb_TenKH;
    private javax.swing.JLabel lb_TimKH;
    private javax.swing.JLabel lb_TongThuCa1;
    private javax.swing.JLabel lb_TongThuCa3;
    private javax.swing.JLabel lb_TongThuCa4;
    private javax.swing.JLabel lbl_TienNhan1;
    private javax.swing.JLabel lbl_TongThue;
    private javax.swing.JPanel pnl_DanhSachSP;
    private javax.swing.JPanel pnl_ThongTin_HD;
    private javax.swing.JPanel pnl_TimKH_row1;
    private javax.swing.JPanel pnl_TimSP;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_thanhToan;
    private javax.swing.JPanel pnl_thongTin;
    private javax.swing.JPanel pnl_thongTin_KH;
    private javax.swing.JPanel pnl_timKH;
    private javax.swing.JScrollPane scroll_DanhSachSP;
    private javax.swing.JTable table_DanhSachSP;
    private javax.swing.JTextField txt_DiemTichLuy;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_SudungTichDiem;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_ThanhToan;
    private javax.swing.JTextField txt_TienNhan;
    private javax.swing.JTextField txt_TienThoi;
    private javax.swing.JTextField txt_TimKH;
    private javax.swing.JTextField txt_TimSP;
    private javax.swing.JTextField txt_TongKM;
    private javax.swing.JTextField txt_TongThue;
    // End of variables declaration//GEN-END:variables
}
