/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.CTHD_NhapHang_DAO;
import dao.HoaDon_NCC_DAO;
import dao.NhaCungCap_DAO;
import dao.SanPham_DAO;
import entity.ChiTietHD_NCC;
import entity.HoaDonNCC;
import entity.NhaCungCap;
import entity.SanPham;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Panel_inventory extends javax.swing.JPanel {

    private NhaCungCap_DAO ncc_dao = new NhaCungCap_DAO();
    private SanPham_DAO sp_dao = new SanPham_DAO();
    private HoaDon_NCC_DAO hdnh_dao = new HoaDon_NCC_DAO();
    private CTHD_NhapHang_DAO cthd_nh_dao = new CTHD_NhapHang_DAO();
    private ArrayList<HoaDonNCC> listHDNCC = new ArrayList<HoaDonNCC>();
    private ArrayList<NhaCungCap> listNCC = new ArrayList<NhaCungCap>();

    private double tongTien = 0;

    /**
     * Creates new form Panel_inventory
     */
    public Panel_inventory() {
        initComponents();

        DocDuLieuLenTableNCC();
        DocDuLieuLenComBoBox_DSNCC();
        docDuLieuHoaDon();
    }

    public void DocDuLieuLenComBoBox_DSNCC() {
        listNCC = ncc_dao.getAllNCC();
        NhaCungCap temp = new NhaCungCap("");
        temp.setTenNCC("Tất cả");
        cbo_NCC.addItem(temp);
        for (NhaCungCap ncc : listNCC) {
            cbo_ncc.addItem(ncc);
            cbo_NCC.addItem(ncc);
        }
    }

    public void docDuLieuHoaDon() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        listHDNCC = hdnh_dao.getAllHDNCC();
        for (HoaDonNCC hd : listHDNCC) {
            String trangThai = hd.isIsThanhToan() ? "Đã thanh toán" : "Chưa thanh toán";
            model.addRow(new Object[]{hd.getMaHDNCC(), hd.getNgayNhap().toString(), hd.getNCC(), trangThai, hd.getGhiChu()});
        }
    }

    public boolean valiData_NCC() {
        String tenNCC = txt_TenNCC.getText().toString().trim();
        String email = txt_Email.getText().toString().trim();
        String sDT = txt_SDT.getText().toString().trim();
        String diaChi = txt_DiaChi.getText().toString().trim();

        if (tenNCC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên NCC không được rỗng!!!");
            return false;
        }

        if (email.isEmpty() || !email.matches("[a-zA-Z0-9]+@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Email theo mẫu abc123@gmail.com");
            return false;
        }

        if (sDT.isEmpty() || !sDT.matches("0\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
            return false;
        }

        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ khoogn được rỗng!!!");
            return false;
        }

        return true;
    }

    public void DocDuLieuLenTableNCC() {
        ArrayList<NhaCungCap> dsNCC = ncc_dao.getAllNCC();
        DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();

        for (NhaCungCap ncc : dsNCC) {
            Object[] obj = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getEmail(), ncc.getSDT()};

            temp.addRow(obj);
        }
    }

    public void XoaDuLieuTableNCC() {
        DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();
        temp.getDataVector().removeAllElements();
    }

    public NhaCungCap createNCC() {
        String maNCC = txt_MaNCC.getText().toString();
        String tenNCC = txt_TenNCC.getText().toString();
        String email = txt_Email.getText().toString();
        String sDT = txt_SDT.getText().toString();
        String diaChi = txt_DiaChi.getText().toString();

        NhaCungCap ncc = new NhaCungCap(maNCC, tenNCC, diaChi, sDT, email);

        return ncc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabbed_NhapHang = new javax.swing.JTabbedPane();
        pnl_QuanLyNCC = new javax.swing.JPanel();
        pnl_ncc_top = new javax.swing.JPanel();
        pnl_thongtin_ncc1 = new javax.swing.JPanel();
        pnl_mancc = new javax.swing.JPanel();
        lb_MaNCC = new javax.swing.JLabel();
        txt_MaNCC = new javax.swing.JTextField();
        pnl_diachi = new javax.swing.JPanel();
        lb_DiaChi = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        pnl_thongtin_ncc2 = new javax.swing.JPanel();
        pnl_sdt = new javax.swing.JPanel();
        lb_SDT = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        pnl_email = new javax.swing.JPanel();
        lb_Email = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        pnl_thongtin_ncc3 = new javax.swing.JPanel();
        pnl_tenncc = new javax.swing.JPanel();
        lb_TenNCC = new javax.swing.JLabel();
        txt_TenNCC = new javax.swing.JTextField();
        pnl_ncc_center = new javax.swing.JPanel();
        pnl_TimKiem_NCC = new javax.swing.JPanel();
        txt_TimKiem_NCC = new javax.swing.JTextField();
        btn_TimKiem_NCC = new javax.swing.JButton();
        scroll_NCC = new javax.swing.JScrollPane();
        table_NCC = new javax.swing.JTable();
        pnl_btn_ncc = new javax.swing.JPanel();
        btn_ThemMoi = new javax.swing.JButton();
        btn_XoaTrang = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        btn_NhapFile = new javax.swing.JButton();
        btn_XuatFile = new javax.swing.JButton();
        pnl_TaoPhieuNhap = new javax.swing.JPanel();
        pnl_TaoPhieu_DanhSachNCC = new javax.swing.JPanel();
        scroll_DanhSachSP = new javax.swing.JScrollPane();
        table_DanhSachSP = new javax.swing.JTable();
        pnl_TaoPhieu_ThongTin = new javax.swing.JPanel();
        pnl_ncc = new javax.swing.JPanel();
        lbl_ncc = new javax.swing.JLabel();
        cbo_ncc = new javax.swing.JComboBox<>();
        pnl_ghichu = new javax.swing.JPanel();
        lbl_ghichu = new javax.swing.JLabel();
        scroll_ghichu = new javax.swing.JScrollPane();
        area_ghiChu = new javax.swing.JTextArea();
        pnl_nhanhang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdio_chuanhan = new javax.swing.JRadioButton();
        radio_nhan = new javax.swing.JRadioButton();
        pnl_tongtien = new javax.swing.JPanel();
        lbl_tongtien = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JTextField();
        pnl_taophieu_thongtin3 = new javax.swing.JPanel();
        btn_TaoHoaDonNCC = new javax.swing.JButton();
        pnl_TimKiem = new javax.swing.JPanel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimSP = new javax.swing.JButton();
        pnl_HoaDonNhapHang = new javax.swing.JPanel();
        pnl_Top = new javax.swing.JPanel();
        pnl_HDNH_TimKiem = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        pnl_LocTheoNcc = new javax.swing.JPanel();
        cbo_NCC = new javax.swing.JComboBox<>();
        pnl_Center = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_QuanLyNCC.setLayout(new java.awt.BorderLayout());

        pnl_ncc_top.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Nhà Cung Cấp"));
        pnl_ncc_top.setMinimumSize(new java.awt.Dimension(10, 150));
        pnl_ncc_top.setPreferredSize(new java.awt.Dimension(10, 150));
        pnl_ncc_top.setLayout(new java.awt.GridLayout(1, 3));

        pnl_thongtin_ncc1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pnl_thongtin_ncc1.setLayout(new java.awt.GridLayout(2, 1));

        pnl_mancc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_mancc.setLayout(new java.awt.BorderLayout());

        lb_MaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_MaNCC.setText("Mã NCC:");
        lb_MaNCC.setPreferredSize(new java.awt.Dimension(65, 20));
        pnl_mancc.add(lb_MaNCC, java.awt.BorderLayout.LINE_START);

        txt_MaNCC.setEditable(false);
        txt_MaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNCCActionPerformed(evt);
            }
        });
        pnl_mancc.add(txt_MaNCC, java.awt.BorderLayout.CENTER);

        pnl_thongtin_ncc1.add(pnl_mancc);

        pnl_diachi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_diachi.setLayout(new java.awt.BorderLayout());

        lb_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_DiaChi.setText("Địa chỉ:");
        lb_DiaChi.setPreferredSize(new java.awt.Dimension(65, 20));
        pnl_diachi.add(lb_DiaChi, java.awt.BorderLayout.LINE_START);

        txt_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_diachi.add(txt_DiaChi, java.awt.BorderLayout.CENTER);

        pnl_thongtin_ncc1.add(pnl_diachi);

        pnl_ncc_top.add(pnl_thongtin_ncc1);

        pnl_thongtin_ncc2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pnl_thongtin_ncc2.setLayout(new java.awt.GridLayout(2, 1));

        pnl_sdt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_sdt.setLayout(new java.awt.BorderLayout());

        lb_SDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_SDT.setText("SĐT:");
        lb_SDT.setPreferredSize(new java.awt.Dimension(50, 20));
        pnl_sdt.add(lb_SDT, java.awt.BorderLayout.LINE_START);

        txt_SDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_sdt.add(txt_SDT, java.awt.BorderLayout.CENTER);

        pnl_thongtin_ncc2.add(pnl_sdt);

        pnl_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_email.setLayout(new java.awt.BorderLayout());

        lb_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Email.setText("Email:");
        lb_Email.setPreferredSize(new java.awt.Dimension(50, 20));
        pnl_email.add(lb_Email, java.awt.BorderLayout.LINE_START);

        txt_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_email.add(txt_Email, java.awt.BorderLayout.CENTER);

        pnl_thongtin_ncc2.add(pnl_email);

        pnl_ncc_top.add(pnl_thongtin_ncc2);

        pnl_thongtin_ncc3.setLayout(new java.awt.GridLayout(2, 1));

        pnl_tenncc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_tenncc.setLayout(new java.awt.BorderLayout());

        lb_TenNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TenNCC.setText("Tên NCC:");
        lb_TenNCC.setPreferredSize(new java.awt.Dimension(70, 20));
        pnl_tenncc.add(lb_TenNCC, java.awt.BorderLayout.LINE_START);

        txt_TenNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_tenncc.add(txt_TenNCC, java.awt.BorderLayout.CENTER);

        pnl_thongtin_ncc3.add(pnl_tenncc);

        pnl_ncc_top.add(pnl_thongtin_ncc3);

        pnl_QuanLyNCC.add(pnl_ncc_top, java.awt.BorderLayout.PAGE_START);

        pnl_ncc_center.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Nhà Cung Cấp"));
        pnl_ncc_center.setPreferredSize(new java.awt.Dimension(670, 559));
        pnl_ncc_center.setLayout(new java.awt.BorderLayout());

        pnl_TimKiem_NCC.setPreferredSize(new java.awt.Dimension(150, 70));

        txt_TimKiem_NCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TimKiem_NCC.setPreferredSize(new java.awt.Dimension(500, 45));
        pnl_TimKiem_NCC.add(txt_TimKiem_NCC);

        btn_TimKiem_NCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_TimKiem_NCC.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_TimKiem_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimKiem_NCCMouseClicked(evt);
            }
        });
        pnl_TimKiem_NCC.add(btn_TimKiem_NCC);

        pnl_ncc_center.add(pnl_TimKiem_NCC, java.awt.BorderLayout.PAGE_START);

        table_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên NCC", "Địa chỉ", "Email", "SĐT"
            }
        ));
        table_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_NCCMouseClicked(evt);
            }
        });
        scroll_NCC.setViewportView(table_NCC);

        pnl_ncc_center.add(scroll_NCC, java.awt.BorderLayout.CENTER);

        pnl_btn_ncc.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_ThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemMoi.setText("Thêm mới");
        btn_ThemMoi.setPreferredSize(new java.awt.Dimension(130, 50));
        btn_ThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMoiMouseClicked(evt);
            }
        });
        btn_ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMoiActionPerformed(evt);
            }
        });
        pnl_btn_ncc.add(btn_ThemMoi);

        btn_XoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaTrang.setText("Xóa trắng");
        btn_XoaTrang.setPreferredSize(new java.awt.Dimension(130, 50));
        btn_XoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseClicked(evt);
            }
        });
        pnl_btn_ncc.add(btn_XoaTrang);

        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.setPreferredSize(new java.awt.Dimension(130, 50));
        btn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseClicked(evt);
            }
        });
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });
        pnl_btn_ncc.add(btn_CapNhat);

        btn_NhapFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_NhapFile.setText("Nhập File");
        btn_NhapFile.setPreferredSize(new java.awt.Dimension(130, 50));
        btn_NhapFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NhapFileMouseClicked(evt);
            }
        });
        pnl_btn_ncc.add(btn_NhapFile);

        btn_XuatFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XuatFile.setText("Xuất File");
        btn_XuatFile.setPreferredSize(new java.awt.Dimension(130, 50));
        btn_XuatFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XuatFileMouseClicked(evt);
            }
        });
        pnl_btn_ncc.add(btn_XuatFile);

        pnl_ncc_center.add(pnl_btn_ncc, java.awt.BorderLayout.PAGE_END);

        pnl_QuanLyNCC.add(pnl_ncc_center, java.awt.BorderLayout.CENTER);

        Tabbed_NhapHang.addTab("Danh sách NCC", pnl_QuanLyNCC);

        pnl_TaoPhieuNhap.setLayout(new java.awt.BorderLayout());

        pnl_TaoPhieu_DanhSachNCC.setLayout(new java.awt.BorderLayout());

        table_DanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng nhập", "Đơn giá nhập", "Thành tiền"
            }
        ));
        scroll_DanhSachSP.setViewportView(table_DanhSachSP);

        pnl_TaoPhieu_DanhSachNCC.add(scroll_DanhSachSP, java.awt.BorderLayout.CENTER);

        pnl_TaoPhieuNhap.add(pnl_TaoPhieu_DanhSachNCC, java.awt.BorderLayout.CENTER);

        pnl_TaoPhieu_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhà cung cấp"));
        pnl_TaoPhieu_ThongTin.setPreferredSize(new java.awt.Dimension(400, 10));
        pnl_TaoPhieu_ThongTin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        pnl_ncc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_ncc.setLayout(new java.awt.BorderLayout());

        lbl_ncc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ncc.setText("Nhà cung cấp:");
        lbl_ncc.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_ncc.add(lbl_ncc, java.awt.BorderLayout.LINE_START);

        cbo_ncc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbo_ncc.setPreferredSize(new java.awt.Dimension(270, 50));
        pnl_ncc.add(cbo_ncc, java.awt.BorderLayout.CENTER);

        pnl_TaoPhieu_ThongTin.add(pnl_ncc);

        pnl_ghichu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_ghichu.setPreferredSize(new java.awt.Dimension(370, 121));
        pnl_ghichu.setLayout(new java.awt.BorderLayout());

        lbl_ghichu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ghichu.setText("Ghi chú:");
        lbl_ghichu.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_ghichu.add(lbl_ghichu, java.awt.BorderLayout.LINE_START);

        scroll_ghichu.setPreferredSize(new java.awt.Dimension(280, 110));

        area_ghiChu.setColumns(20);
        area_ghiChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        area_ghiChu.setRows(5);
        area_ghiChu.setPreferredSize(new java.awt.Dimension(270, 104));
        scroll_ghichu.setViewportView(area_ghiChu);

        pnl_ghichu.add(scroll_ghichu, java.awt.BorderLayout.CENTER);

        pnl_TaoPhieu_ThongTin.add(pnl_ghichu);

        pnl_nhanhang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_nhanhang.setPreferredSize(new java.awt.Dimension(370, 31));
        pnl_nhanhang.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setPreferredSize(new java.awt.Dimension(90, 16));
        pnl_nhanhang.add(jLabel1);

        rdio_chuanhan.setText("Chưa nhận");
        pnl_nhanhang.add(rdio_chuanhan);

        radio_nhan.setText("Đã nhận");
        pnl_nhanhang.add(radio_nhan);

        pnl_TaoPhieu_ThongTin.add(pnl_nhanhang);

        pnl_tongtien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        pnl_tongtien.setLayout(new java.awt.BorderLayout());

        lbl_tongtien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_tongtien.setText("Tổng tiền:");
        lbl_tongtien.setPreferredSize(new java.awt.Dimension(100, 20));
        pnl_tongtien.add(lbl_tongtien, java.awt.BorderLayout.LINE_START);

        txt_tongtien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_tongtien.setPreferredSize(new java.awt.Dimension(270, 50));
        pnl_tongtien.add(txt_tongtien, java.awt.BorderLayout.CENTER);

        pnl_TaoPhieu_ThongTin.add(pnl_tongtien);

        pnl_taophieu_thongtin3.setPreferredSize(new java.awt.Dimension(400, 50));

        btn_TaoHoaDonNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TaoHoaDonNCC.setText("Tạo đơn nhập");
        btn_TaoHoaDonNCC.setPreferredSize(new java.awt.Dimension(200, 45));
        btn_TaoHoaDonNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaoHoaDonNCCMouseClicked(evt);
            }
        });
        btn_TaoHoaDonNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoHoaDonNCCActionPerformed(evt);
            }
        });
        pnl_taophieu_thongtin3.add(btn_TaoHoaDonNCC);

        pnl_TaoPhieu_ThongTin.add(pnl_taophieu_thongtin3);

        pnl_TaoPhieuNhap.add(pnl_TaoPhieu_ThongTin, java.awt.BorderLayout.EAST);

        pnl_TimKiem.setPreferredSize(new java.awt.Dimension(200, 70));
        pnl_TimKiem.setLayout(new java.awt.BorderLayout());

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TimKiem.setText("Nhập mã SP...");
        txt_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiemActionPerformed(evt);
            }
        });
        pnl_TimKiem.add(txt_TimKiem, java.awt.BorderLayout.CENTER);

        btn_TimSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TimSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_TimSP.setPreferredSize(new java.awt.Dimension(70, 70));
        btn_TimSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimSPMouseClicked(evt);
            }
        });
        pnl_TimKiem.add(btn_TimSP, java.awt.BorderLayout.EAST);

        pnl_TaoPhieuNhap.add(pnl_TimKiem, java.awt.BorderLayout.NORTH);

        Tabbed_NhapHang.addTab("Tạo phiếu nhập hàng", pnl_TaoPhieuNhap);

        pnl_HoaDonNhapHang.setLayout(new java.awt.BorderLayout());

        pnl_Top.setPreferredSize(new java.awt.Dimension(0, 100));
        pnl_Top.setLayout(new java.awt.GridLayout(1, 2));

        pnl_HDNH_TimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm hóa đơn nhâp hàng"));
        pnl_HDNH_TimKiem.setPreferredSize(new java.awt.Dimension(10, 70));
        pnl_HDNH_TimKiem.setLayout(new java.awt.BorderLayout());

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnl_HDNH_TimKiem.add(jTextField2, java.awt.BorderLayout.CENTER);

        btn_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_timKiem.setPreferredSize(new java.awt.Dimension(70, 50));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        pnl_HDNH_TimKiem.add(btn_timKiem, java.awt.BorderLayout.EAST);

        pnl_Top.add(pnl_HDNH_TimKiem);

        pnl_LocTheoNcc.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc Theo Nhà Cung Cấp"));
        pnl_LocTheoNcc.setLayout(new java.awt.BorderLayout());

        cbo_NCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbo_NCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_NCCItemStateChanged(evt);
            }
        });
        pnl_LocTheoNcc.add(cbo_NCC, java.awt.BorderLayout.CENTER);

        pnl_Top.add(pnl_LocTheoNcc);

        pnl_HoaDonNhapHang.add(pnl_Top, java.awt.BorderLayout.NORTH);

        pnl_Center.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phiếu nhập", "Ngày nhập", "Nhà cung cấp", "Trạng thái", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        pnl_Center.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnl_HoaDonNhapHang.add(pnl_Center, java.awt.BorderLayout.CENTER);

        Tabbed_NhapHang.addTab("Hóa đơn nhập hàng", pnl_HoaDonNhapHang);

        add(Tabbed_NhapHang, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void table_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NCCMouseClicked
        // TODO add your handling code here:
        int r = table_NCC.getSelectedRow();

        if (r >= 0) {
            txt_MaNCC.setText(table_NCC.getValueAt(r, 0).toString());
            txt_TenNCC.setText(table_NCC.getValueAt(r, 1).toString());
            txt_SDT.setText(table_NCC.getValueAt(r, 4).toString());
            txt_Email.setText(table_NCC.getValueAt(r, 3).toString());
            txt_DiaChi.setText(table_NCC.getValueAt(r, 2).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng muốn thao tác!!!");
        }
    }//GEN-LAST:event_table_NCCMouseClicked

    private void btn_ThemMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiMouseClicked
        // TODO add your handling code here:
        if (valiData_NCC()) {
            NhaCungCap ncc = createNCC();
            ncc.setMaNCC(ncc_dao.phatSinhMaTuDong());
            ArrayList<NhaCungCap> dsNCC = ncc_dao.getAllNCC();

            if (true) {
                if (ncc_dao.ThemNCC(ncc)) {
                    txt_MaNCC.setText("");
                    txt_TenNCC.setText("");
                    txt_DiaChi.setText("");
                    txt_Email.setText("");
                    txt_SDT.setText("");

                    txt_MaNCC.setFocusable(true);
                    XoaDuLieuTableNCC();
                    DocDuLieuLenTableNCC();
                    JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bai!!! Có lỗi xảy ra!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nhà cung cấp đã tồn tai!!!");
            }
        }
    }//GEN-LAST:event_btn_ThemMoiMouseClicked

    private void btn_TimKiem_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimKiem_NCCMouseClicked
        // TODO add your handling code here:
        String maNCC_searched = txt_TimKiem_NCC.getText().toString().trim();

        if (!maNCC_searched.trim().equals("")) {
            XoaDuLieuTableNCC();

            NhaCungCap ncc = null;

            for (NhaCungCap i : listNCC) {
                if (i.getMaNCC().equals(maNCC_searched)) {
                    ncc = i;
                    break;
                }
            }
            if (ncc == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy");
                return;
            }
            DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();
            Object[] obj = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getEmail(), ncc.getSDT()};
            temp.addRow(obj);
        } else {
            XoaDuLieuTableNCC();
            DocDuLieuLenTableNCC();
        }
    }//GEN-LAST:event_btn_TimKiem_NCCMouseClicked

    private void btn_CapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseClicked
        // TODO add your handling code here:

        int r = table_NCC.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(this, "Chọn NCC cần cập nhật!!!");
        }

        if (valiData_NCC()) {
            String maNCC = txt_MaNCC.getText().toString();
            String tenNCC = txt_TenNCC.getText().toString();
            String email = txt_Email.getText().toString();
            String sDT = txt_SDT.getText().toString();
            String diaChi = txt_DiaChi.getText().toString();

            NhaCungCap ncc = new NhaCungCap(maNCC, tenNCC, diaChi, sDT, email);

            if (ncc_dao.CapNhatNCC(ncc)) {
                txt_MaNCC.setText("");
                txt_TenNCC.setText("");
                txt_DiaChi.setText("");
                txt_Email.setText("");
                txt_SDT.setText("");

                txt_MaNCC.setFocusable(true);
                DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();
                temp.removeRow(r);
                Object[] obj = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getEmail(), ncc.getSDT()};
                temp.insertRow(r, obj);

                JOptionPane.showMessageDialog(this, "Cập nhật thành công NCC có mã = " + maNCC);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bai!!! Có lỗi xảy ra!!!");
            }
        }

    }//GEN-LAST:event_btn_CapNhatMouseClicked

    private void btn_XoaTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseClicked
        // TODO add your handling code here:
        txt_MaNCC.setText("");
        txt_TenNCC.setText("");
        txt_DiaChi.setText("");
        txt_Email.setText("");
        txt_SDT.setText("");

        txt_MaNCC.setFocusable(true);
    }//GEN-LAST:event_btn_XoaTrangMouseClicked

    private void txt_MaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNCCActionPerformed

    private void btn_TimSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimSPMouseClicked
        // TODO add your handling code here:
        String maSP = txt_TimKiem.getText();
        SanPham sp = sp_dao.getSP_TheoMa(maSP);

        if (maSP.compareTo("") != 0 && sp != null) {
//            tmp.add(sp);
//            tienVon += sp.getGiaNhapHang();
//            tongKM += sp.getkM().getLoaiKM().equals("LKM001") 
//                        ? sp.getGiaBan() * sp.getkM().getGiaTriKhuyenMai()
//                        : sp.getkM().getGiaTriKhuyenMai();
//            tongThue += sp.getThue();

            // Nhập số lượng sản phẩm
            int soLuong = Integer.parseInt(JOptionPane.showInputDialog(null, "Nhập số lượng", 0));

            // Tính tổng tiền thanh toán
            tongTien += sp.getGiaNhapHang() * soLuong;
            txt_tongtien.setText(tongTien + "");

            // Lấy số lượng hàng đang có
            int n = table_DanhSachSP.getModel().getRowCount();

            // Kiểm tra sản phẩm trùng lặp: cộng dồn số lượng và thành tiền
            for (int i = 0; i < n; ++i) {
                String maSP_Cheked = table_DanhSachSP.getModel().getValueAt(i, 0).toString();
                if (maSP_Cheked.compareTo(maSP) == 0) {
                    int soLuongHienTai = Integer.parseInt(table_DanhSachSP.getModel().getValueAt(i, 2).toString());
                    int soLuongMoi = soLuongHienTai + soLuong;
                    table_DanhSachSP.getModel().setValueAt(soLuongMoi, i, 2);

                    table_DanhSachSP.getModel().setValueAt(
                            Double.parseDouble(table_DanhSachSP.getValueAt(i, 3).toString()) * soLuongMoi, i, 4);
                    return;
                }
            }

            // Them sp vao giao hang
//            Object[] obj;
//                double donGia = sp.getGiaBan() * (1 - sp.getkM().getGiaTriKhuyenMai() + sp.getThue());
            Object[] obj = {sp.getMaSP(), sp.getTenSP(), soLuong,
                sp.getGiaNhapHang(), sp.getGiaNhapHang() * soLuong};
            DefaultTableModel model_DSSP = (DefaultTableModel) table_DanhSachSP.getModel();
            model_DSSP.addRow(obj);
//            if(sp.getkM().getLoaiKM().equals("LKM001")) {
//            } else {
//                double donGia = sp.getGiaBan() * (1 - sp.getThue()) - sp.getkM().getGiaTriKhuyenMai();
//                Object[] obj = {sp.getMaSP(), sp.getTenSP(), sp.getLoaiSP(), soLuong, sp.getThue(), sp.getkM().getGiaTriKhuyenMai(), 
//                                        donGia ,donGia * soLuong};
//                model_DSSP = (DefaultTableModel)table_DanhSachSP.getModel();
//                model_DSSP.addRow(obj);
//            }
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm");
        }
    }//GEN-LAST:event_btn_TimSPMouseClicked

    public void XoaHetDuLieuSP_HDNH() {
        DefaultTableModel temp = (DefaultTableModel) table_DanhSachSP.getModel();
        temp.getDataVector().removeAllElements();
    }

    private void btn_TaoHoaDonNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaoHoaDonNCCMouseClicked
        // TODO add your handling code here:

        // Luu hoa don nhap hang
        String maHDNH = hdnh_dao.TuPhatSinhMa();
        int n = cbo_ncc.getSelectedIndex() + 1;
        String maNCC = n < 10 ? "NCC00" + n
                : n < 100 ? "NCC0" + n
                        : "NCC" + n;
        LocalDateTime ngayNhap = LocalDateTime.now();
        String ghiChu = area_ghiChu.getText();
        boolean isThanhToan = radio_nhan.isSelected();

        HoaDonNCC hdnh = new HoaDonNCC(maHDNH, new NhaCungCap(maNCC), ngayNhap, ghiChu, isThanhToan);
        if (hdnh_dao.ThemHDNCCVaoCSDL(hdnh)) {
            docDuLieuHoaDon();
            JOptionPane.showMessageDialog(this, "Lưu hóa đơn thành công!");

            // Luu chi tiet hoa don
            int soLuongSp = table_DanhSachSP.getRowCount();
            for (int i = 0; i < soLuongSp; i++) {
                String maSP = table_DanhSachSP.getValueAt(i, 0).toString();
                int soLuong = Integer.parseInt(table_DanhSachSP.getValueAt(i, 2).toString());

//                ChiTietHD_NCC temp = null;
                SanPham sp = new SanPham();
                sp.setMaSP(maSP);
                ChiTietHD_NCC temp = new ChiTietHD_NCC(sp, hdnh, soLuong);
                cthd_nh_dao.ThemVaoCSDL(temp);
            }

            area_ghiChu.setText("");
            cbo_ncc.setSelectedIndex(0);
            XoaHetDuLieuSP_HDNH();
        }

    }//GEN-LAST:event_btn_TaoHoaDonNCCMouseClicked

    private void btn_NhapFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NhapFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NhapFileMouseClicked

    private void btn_XuatFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XuatFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XuatFileMouseClicked

    private void txt_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiemActionPerformed

    private void btn_TaoHoaDonNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoHoaDonNCCActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_TaoHoaDonNCCActionPerformed

    private void cbo_NCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_NCCItemStateChanged
        // TODO add your handling code here:
        NhaCungCap ncc = (NhaCungCap) cbo_NCC.getSelectedItem();
        if (ncc.getMaNCC().equals("")) {
            docDuLieuHoaDon();
        } else {
            ArrayList<HoaDonNCC> temp = new ArrayList<HoaDonNCC>();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            for (HoaDonNCC i : listHDNCC) {
                if (i.getNCC().getMaNCC().equals(ncc.getMaNCC())) {
                    temp.add(i);
                }
            }

            model.setRowCount(0);
            for (HoaDonNCC hd : temp) {
                String trangThai = hd.isIsThanhToan() ? "Đã thanh toán" : "Chưa thanh toán";
                model.addRow(new Object[]{hd.getMaHDNCC(), hd.getNgayNhap().toString(), hd.getNCC(), trangThai, hd.getGhiChu()});
            }
        }
    }//GEN-LAST:event_cbo_NCCItemStateChanged

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        String timKiemText = jTextField2.getText().toString().trim();
        HoaDonNCC hd = null;
        ArrayList<HoaDonNCC> temp = new ArrayList<HoaDonNCC>();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (timKiemText.equals("")) {
            docDuLieuHoaDon();
            return;
        }
        for (HoaDonNCC i : listHDNCC) {
            if (i.getMaHDNCC().equals(timKiemText)) {
                hd = i;
            }
        }
        if (hd != null) {
            model.setRowCount(0);
            String trangThai = hd.isIsThanhToan() ? "Đã thanh toán" : "Chưa thanh toán";
            model.addRow(new Object[]{hd.getMaHDNCC(), hd.getNgayNhap().toString(), hd.getNCC(), trangThai, hd.getGhiChu()});
        } else
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMoiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_ThemMoiActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabbed_NhapHang;
    private javax.swing.JTextArea area_ghiChu;
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_NhapFile;
    private javax.swing.JButton btn_TaoHoaDonNCC;
    private javax.swing.JButton btn_ThemMoi;
    private javax.swing.JButton btn_TimKiem_NCC;
    private javax.swing.JButton btn_TimSP;
    private javax.swing.JButton btn_XoaTrang;
    private javax.swing.JButton btn_XuatFile;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JComboBox<NhaCungCap> cbo_NCC;
    private javax.swing.JComboBox<NhaCungCap> cbo_ncc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb_DiaChi;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_MaNCC;
    private javax.swing.JLabel lb_SDT;
    private javax.swing.JLabel lb_TenNCC;
    private javax.swing.JLabel lbl_ghichu;
    private javax.swing.JLabel lbl_ncc;
    private javax.swing.JLabel lbl_tongtien;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_HDNH_TimKiem;
    private javax.swing.JPanel pnl_HoaDonNhapHang;
    private javax.swing.JPanel pnl_LocTheoNcc;
    private javax.swing.JPanel pnl_QuanLyNCC;
    private javax.swing.JPanel pnl_TaoPhieuNhap;
    private javax.swing.JPanel pnl_TaoPhieu_DanhSachNCC;
    private javax.swing.JPanel pnl_TaoPhieu_ThongTin;
    private javax.swing.JPanel pnl_TimKiem;
    private javax.swing.JPanel pnl_TimKiem_NCC;
    private javax.swing.JPanel pnl_Top;
    private javax.swing.JPanel pnl_btn_ncc;
    private javax.swing.JPanel pnl_diachi;
    private javax.swing.JPanel pnl_email;
    private javax.swing.JPanel pnl_ghichu;
    private javax.swing.JPanel pnl_mancc;
    private javax.swing.JPanel pnl_ncc;
    private javax.swing.JPanel pnl_ncc_center;
    private javax.swing.JPanel pnl_ncc_top;
    private javax.swing.JPanel pnl_nhanhang;
    private javax.swing.JPanel pnl_sdt;
    private javax.swing.JPanel pnl_taophieu_thongtin3;
    private javax.swing.JPanel pnl_tenncc;
    private javax.swing.JPanel pnl_thongtin_ncc1;
    private javax.swing.JPanel pnl_thongtin_ncc2;
    private javax.swing.JPanel pnl_thongtin_ncc3;
    private javax.swing.JPanel pnl_tongtien;
    private javax.swing.JRadioButton radio_nhan;
    private javax.swing.JRadioButton rdio_chuanhan;
    private javax.swing.JScrollPane scroll_DanhSachSP;
    private javax.swing.JScrollPane scroll_NCC;
    private javax.swing.JScrollPane scroll_ghichu;
    private javax.swing.JTable table_DanhSachSP;
    private javax.swing.JTable table_NCC;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNCC;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNCC;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_TimKiem_NCC;
    private javax.swing.JTextField txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
